### ISSUE TITLE
JHourMinuteChooser currentTime checkbox doesn't respect the enabled property

### ISSUE THREAD

**Issue by TeamDman** [javatlacati/jcalendar#2]
In my example, I have a checkbox labeled `Offset date` which toggles the enabled property of the JHourMinuteChooser component.
However, the `currentTime` checkbox of the component interferes even when the JHourMinuteChooser is set to disabled.
![jXAEgdMarW](https://user-images.githubusercontent.com/9356891/71552949-188e3580-29d4-11ea-99ca-41574eacbd53.gif)

Expected behaviour:
- currentTime checkbox is also disabled when the JHourMinuteChooser is disabled
- currentTime checkbox hover events shouldn't reenable the JHourMinuteChooser

**Comment by javatlacati** [comment]
Can you please try again?

**Comment by TeamDman** [comment]
Confirmed fixed, thanks!
